/** @type {import('tailwindcss').Config} */
module.exports = {
  mode: 'jit',
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      content: {
        'link': 'url("/image/rank-side-star.webp")',
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        'btn-gradient': 'linear-gradient(to right, #1163fb, #9c3aed)',
        "offwhite-gradient": 'linear-gradient(90deg, rgb(242, 244, 248) 70%, rgba(242, 244, 248, .1))',
        "edgeGradient": 'linear-gradient(to right, #00949a, #f7cc23, #000)',
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
        'text-gradient': 'linear-gradient(to right, #dc2626, #1d4ed8)',
        'custom-image': "url('/image/slider-home/asfdasda.jpg')",
        'About': "url('/image/lab/User-Manual-AKGEC 5.webp')",
        'Academics': "url('/image/lab/User-Manual-AKGEC 6.webp')",
        'Placement': "url('/image/building/building8.webp')",
        'Research': "url('/image/lab/User-Manual-AKGEC 1.webp')",
        'svgElement': "url('/image/skills-sprite.webp')",
        'world-map': "url('/image/placements/world-map.png')",
        'staff-bg': "url('/image/placements/staff-bg.jpg')",
        'Header': "url('/image/header-img.jpg')",

        'Edge': "url('/image/edge-banner.jpg')",
        'Empathy': "url('/image/core-value/empathy.webp')",
        'HumanDignity': "url('/image/core-value/human-dignity.webp')",
        'Giving': "url('/image/core-value/giving.webp')",
        'PaperBackground': "url('/image/background-paper.png')",
        'BG2': "url('/image/MainBG2.jpg')",
        'BG3': "url('/image/MainBG.jpg')",
        'BG4': "url('/image/dotted-map-bg.webp')",
        'BG5': "url('/image/dotted-map-bg.png')",
        'BG6': "url('/image/AKG_Student.jpg')",
        'BG7': "url('/image/academic-overview/bg-1.jpg')",
        'BG8': "url('/image/academic-overview/bg-2.jpg')",
        'BG9': "url('/image/academic-overview/bg-3.jpg')",
        'BG10': "url('/image/academic-overview/bg-4.jpg')",
        'BG11': "url('/image/woman-bg.jpg')",
        'BG12': "url('/image/main-banner.jpg')",
        'BG13': "url('/image/esteemed-partners-bg.jpg')",
        'BG14': "url('/image/lab/User-Manual-AKGEC 5.webp')",
        'BG15': "url('/image/placements/8464.png')",
        'BG16': "url('/image/building/building4.webp')",
        'BG17': "url('/image/recognitions-and-approvals/bottom-banner-bg.jpg')",
        'BG18': "url('/image/scholarship/bottom-banner-bg.jpg')",
        'BG19': "url('/image/awards-and-ranking/banner-bg.jpg')",
        'BG20': "url('/image/Pages/545.jpg')",
        'BG21': "url('/image/Pages/546.jpg')",
        'BG22': "url('/image/Pages/547.jpg')",
        'BG23': "url('/image/Pages/548.jpg')",
        'BG24': "url('/image/Pages/549.jpg')",
        'BG25': "url('/image/Pages/550.jpg')",
        'BG26': "url('/image/placements/middle-banner.jpg')",
        'BG27': "url('/image/convocation/convocation-banner.jpg')",
        'BG28': "url('/image/placements/career-banner.jpg')",
        'BG29': "url('/image/environment-protection/middle-banner.webp')",
        'BG30': "url('/image/tech-invent-&-events/tech-invent-banner.jpg')",
        'BG31': "url('/image/tbi/banner-bg-4.jpg')",
        'BG32': "url('/image/tbi/rabindranath-tagore-.jpg')",
        'BG33': "url('/image/center-of-research/astronaut.jpg')",
        'BG34': "url('/image/center-of-research/build.jpg')",
        'BG35': "url('/image/scholars/scholars.jpg')",
        'BG36': "url('/image/schools/banner-1.jpg')",
        'BG37': "url('/image/schools/banner-2.jpg')",
        'BG38': "url('/image/schools/banner-3.jpg')",
        'BG39': "url('/image/national-admission/bottom-banner.jpg')",
        'BG40': "url('/image/national-admission/main-banner.jpg')",
        'BG41': "url('/image/building/building1.webp')",
        'BG42': "url('/image/building/building2.webp')",
        'BG43': "url('/image/building/building3.webp')",
        'BG44': "url('/image/building/building4.webp')",
        'BG45': "url('/image/building/building5.webp')",
        'BG46': "url('/image/building/building6.webp')",
        'BG47': "url('/image/building/building7.webp')",
        'BG48': "url('/image/building/building8.webp')",
        'BG49': "url('/image/building/building9.webp')",
        'BG50': "url('/image/building/building10.webp')",

        'BG-Building-1': "url('/image/building/building-11.webp')",
        'BG-Building-2': "url('/image/building/building-12.webp')",
        'BG-Building-3': "url('/image/building/building-13.webp')",
        'BG-Building-4': "url('/image/building/building-14.webp')",
        'BG-Building-5': "url('/image/building/building-15.webp')",
        'BG-Building-6': "url('/image/building/building-16.webp')",
        'BG-Building-7': "url('/image/building/building-17.webp')",
        'BG-Building-8': "url('/image/building/building-18.webp')",
        'BG-Building-9': "url('/image/building/building-19.webp')",
        'BG-Building-10': "url('/image/building/building-20.webp')",
        'BG-Building-11': "url('/image/building/building-21.webp')",
        'BG-Building-12': "url('/image/building/building-22.webp')",
        'BG-Building-13': "url('/image/building/building-23.webp')",
        'BG-Building-14': "url('/image/building/building-24.webp')",

      },
      boxShadow: {
        'cardShadow': '0 0.5rem 1rem rgba(0, 0, 0, 0.15)',
      },
      screens: {
        'break1': '1800px',
        'break2': '1400px',
        'break3': '1200px',
        'break4': '992px',
      },
    },
    fontFamily: {
      novaReg: ['nova-regular', 'proximanova-regular'],
      novaSemi: ['nova-semibold', 'proximanova-semibold'],
      novaBold: ['nova-bold', 'proximanova-bold'],
      novaLight: ['nova-light', 'proximanova-light'],
      novaThin: ['nova-thin', 'proximanova-thin'],
      slick: ['slick', 'slick'],
      montserrat: ['montserrat', 'montserrat'],
      cursiveFont: ['cursiveFont', 'sans-serif'],
    },
    keyframes: {
      zoomInOut: {
        '0%, 100%': { transform: 'scale(1)' },
        '50%': { transform: 'scale(1.2)' },
      },
      scroll: {
        to: {
          transform: 'translate(calc(-50% - 0.5rem))',
        },
      },
    },
    animation: {
      zoomInOut: 'zoomInOut 16s ease-in-out infinite',
      scroll: 'scroll var(--animation-duration, 60s) var(--animation-direction, forwards) linear infinite',
    },
  },
  plugins: [
    require('tailwind-scrollbar'),
    require("@tailwindcss/typography"),
  ],
};

