export const facultyData = [
    { id: 1, name: "Dr. Anu Chaudhary", education: "Ph.D", designation: "Professor & HOD", img: "/image/faculty/1.jpg" },
    { id: 2, name: "Dr. Rajesh Prasad", education: "Ph.D", designation: "Professor", img: "/image/faculty/3.jpg" },
    { id: 3, name: "Dr. Avdhesh Gupta", education: "Ph.D", designation: "Professor", img: "/image/faculty/4.jpg" },
    { id: 4, name: "Dr. Ayushi Prakash", education: "Ph.D", designation: "Professor", img: "/image/faculty/5.jpg" },
    { id: 5, name: "Dr. Shashank Sahu", education: "Ph.D", designation: "Professor", img: "/image/faculty/2.jpg" },
    { id: 6, name: "Dr. Sonam Gupta", education: "Ph.D", designation: "Professor", img: "/image/faculty/6.jpg" },
    { id: 7, name: "Dr. Inderjeet Kaur", education: "Ph.D", designation: "Professor", img: "/image/faculty/7.jpg" },
    { id: 8, name: "Dr. Santosh Kumar", education: "Ph.D", designation: "Associate Professor", img: "/image/faculty/8.jpg" },
    { id: 9, name: "Dr. Akhilesh Verma", education: "Ph.D", designation: "Associate Professor", img: "/image/faculty/9.jpg" },
    { id: 10, name: "Dr. Anuradha", education: "Ph.D", designation: "Associate Professor", img: "/image/faculty/10.jpg" },
    { id: 11, name: "Dr. Jaishree Jain", education: "Ph.D", designation: "Associate Professor", img: "/image/faculty/11.jpg" },
    { id: 12, name: "Dr. Nishant Kumar Pathak", education: "Ph.D", designation: "Associate Professor", img: "/image/faculty/12.jpg" },
    { id: 13, name: "Dr. Pawan", education: "Ph.D", designation: "Associate Professor", img: "/image/faculty/13.png" },
    { id: 14, name: "Dr. Ashish Dixit", education: "Ph.D", designation: "Associate Professor", img: "/image/faculty/14.jpg" },
    { id: 15, name: "Dr. Shiva Tyagi", education: "M.Tech, Ph.D", designation: "Assistant Professor", img: "/image/faculty/15.jpg" },
    { id: 16, name: "Mr. B.N Pandey", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/16.jpg" },
    { id: 17, name: "Mr. Pradeep Gupta", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/17.jpg" },
    { id: 18, name: "Mr. Pronab Kumar Adhikari", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/18.jpg" },
    { id: 19, name: "Mr. Vishal Chaudhary", education: "M.Tech", designation: "Assistant Professor", img: "/image/faculty/19.jpg" },
    { id: 20, name: "Mr. Vishal Jayaswal", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/20.jpg" },
    { id: 21, name: "Ms. Neerja Arora", education: "M.Tech", designation: "Assistant Professor", img: "/image/faculty/21.jpg" },
    { id: 22, name: "Ms. Rekha Baghel", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/22.jpg" },
    { id: 23, name: "Mr. Yogendra Narayan Prajapati", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/23.jpg" },
    { id: 24, name: "Ms. Kamna Singh", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/24.jpg" },
    { id: 25, name: "Ms. Amrita Bhatnagar", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/25.jpg" },
    { id: 26, name: "Ms. Juli Yadav", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/26.jpg" },
    { id: 27, name: "Ms. Sonali", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/27.jpg" },
    { id: 28, name: "Mr. Sandeep Yadav", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/28.jpg" },
    { id: 29, name: "Mr. Anuj Kumar", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/29.jpg" },
    { id: 30, name: "Mr. Manish Kumar", education: "M.Tech", designation: "Assistant Professor", img: "/image/faculty/30.jpg" },
    { id: 31, name: "Dr. Upasana Mishra", education: "Ph.D", designation: "Assistant Professor", img: "/image/faculty/31.jpg" },
    { id: 32, name: "Ms. Harnit Saini", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/32.jpeg" },
    { id: 33, name: "Mr. Samendra Singh", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/33.jpg" },
    { id: 34, name: "Ms. Ankita Rani", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/34.jpg" },
    { id: 35, name: "Ms. Swati Tomar", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/35.jpg" },
    { id: 36, name: "Mr. Sharma Ji", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/36.jpg" },
    { id: 37, name: "Mr. Manoj Kumar", education: "M.Tech", designation: "Assistant Professor", img: "/image/faculty/37.jpg" },
    { id: 38, name: "Mr. Sharvan Kumar", education: "M.Tech", designation: "Assistant Professor", img: "/image/faculty/38.jpg" },
    { id: 39, name: "Ms. Pooja Sharma", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/39.jpg" },
    { id: 40, name: "Mr. Vikas", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/40.jpg" },
    { id: 41, name: "Mr. Sachin Jain", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/41.jpg" },
    { id: 42, name: "Mr. Amit Goel", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/42.jpg" },
    { id: 43, name: "Mr. Bhupesh Kumar Gupta", education: "M.Tech", designation: "Assistant Professor", img: "/image/faculty/43.jpg" },
    { id: 44, name: "Mr. Mradul Kumar Jain", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/44.jpg" },
    { id: 45, name: "Ms. Neeti Pahuja", education: "M.Tech", designation: "Assistant Professor", img: "/image/faculty/45.jpg" },
    { id: 46, name: "Mr. Ashish Kumar-II", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/46.jpg" },
    { id: 47, name: "Ms. Bhumica", education: "M.Tech", designation: "Assistant Professor", img: "/image/faculty/47.jpg" },
    { id: 48, name: "Ms. Mahima Saxena", education: "M.Tech", designation: "Assistant Professor", img: "/image/faculty/48.jpg" },
    { id: 49, name: "Ms. Dhanshri Parihar", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/49.jpg" },
    { id: 50, name: "Mr. Updesh Kumar Jaiswal", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/50.jpg" },
    { id: 51, name: "Dr. Manoj Kumar Srivastava", education: "M.Tech, Ph.D", designation: "Assistant Professor", img: "/image/faculty/51.jpg" },
    { id: 52, name: "Ms. Ritika Dhyani", education: "M.Tech", designation: "Assistant Professor", img: "/image/faculty/52.jpg" },
    { id: 53, name: "Ms. Khushbu Malviya", education: "M.Tech", designation: "Assistant Professor", img: "/image/faculty/53.jpg" },
    { id: 54, name: "Ms. Vaishali Deshwal", education: "M.Tech", designation: "Assistant Professor", img: "/image/faculty/54.jpg" },
    { id: 55, name: "Ms. Gunjan Saxena", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/55.jpg" },
    { id: 56, name: "Mr. Amit Kumar", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/56.jpg" },
    { id: 57, name: "Mr. Beerbal Solanki", education: "M.Tech", designation: "Assistant Professor", img: "/image/faculty/57.jpg" },
    { id: 58, name: "Ms. Manisha Rai", education: "M.Tech", designation: "Assistant Professor", img: "/image/faculty/58.jpg" },
    { id: 59, name: "Mr. Mayank Trivedi", education: "M.Tech", designation: "Assistant Professor", img: "/image/faculty/59.jpg" },
    { id: 60, name: "Mr. Surendar Kumar", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/60.jpg" },
    { id: 61, name: "Ms. Neeharika Tripathi", education: "M.Tech", designation: "Assistant Professor", img: "/image/faculty/61.jpg" },
    { id: 62, name: "Mr. Arviind Goutam", education: "M.Tech", designation: "Assistant Professor", img: "/image/faculty/62.jpg" },
    { id: 63, name: "Ms. Amrita Tiwari", education: "M.Tech", designation: "Assistant Professor", img: "/image/faculty/63.jpg" },
    { id: 64, name: "Mr. Pushkal Kumar Shukla", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/64.jpg" },
    { id: 65, name: "Ms. Hina Singh", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/65.jpg" },
    { id: 66, name: "Ms. Rupa Rani", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/66.png" },
    { id: 67, name: "Ms. Rachana Singh Sisodia", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/67.png" },
    { id: 68, name: "Ms. Vibha Srivastava", education: "M.Tech", designation: "Assistant Professor", img: "/image/faculty/68.jpg" },
    { id: 69, name: "Ms. Anuradha Dhumale", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/69.jpg" },
    { id: 70, name: "Mr. Shiv Pratap Singh Kushwaha", education: "M.Tech, Ph.D*", designation: "Assistant Professor", img: "/image/faculty/70.jpg" },
    { id: 71, name: "Mr. Vivek Agarwal", education: "M.Tech", designation: "Assistant Professor", img: "/image/faculty/71.jpg" },
    { id: 72, name: "Dr. Sneha Mishra", education: "Ph.D", designation: "Assistant Professor", img: "/image/faculty/72.jpg" },
    { id: 73, name: "Dr. Saroj Kushwah", education: "Ph.D", designation: "Assistant Professor", img: "/image/faculty/73.jpg" },
    { id: 74, name: "Ms. Kriti Mishra", education: "M.Tech", designation: "Assistant Professor", img: "/image/faculty/74.jpg" },
    { id: 75, name: "Mr. Eshank Jain", education: "M.Tech", designation: "Assistant Professor", img: "/image/faculty/75.jpg" },
    { id: 76, name: "Dr. Neha Singh", education: "Ph.D", designation: "Assistant Professor", img: "/image/faculty/76.jpg" },
    { id: 77, name: "Mr. Gaurav Kumar", education: "M.Tech", designation: "Assistant Professor", img: "/image/faculty/77.jpg" },
    { id: 78, name: "Mr. Pramod Kumar Shukla", education: "B.Tech", designation: "Adjunct Faculty", img: "/image/faculty/78.jpg" },
    { id: 79, name: "Mr. Rajesh Kumar Prajapati", education: "B.Tech", designation: "Adjunct Faculty", img: "/image/faculty/79.jpg" },
    { id: 80, name: "Mr. Nagendra Kumar Yadav", education: "B.Tech", designation: "Adjunct Faculty", img: "/image/faculty/80.jpg" },
    { id: 81, name: "Mr. Mridul Bhardwaj", education: "MCA, Ph.D", designation: "Adjunct Faculty", img: "/image/faculty/81.jpg" },
    { id: 82, name: "Mr. Manoj Kumar", education: "B.Tech", designation: "Adjunct Faculty", img: "/image/faculty/82.jpg" },
    { id: 83, name: "Ms. Priyanka Sharma", education: "B.Tech, M.Tech", designation: "Adjunct Faculty", img: "/image/faculty/83.jpg" },
    { id: 84, name: "Mr. Vishal Vinay Majumdar", education: "B.Tech", designation: "Adjunct Faculty", img: "/image/faculty/84.jpg" },
];