export const facultyData = [
  {
    name: "Dr. Lokesh Varshney",
    title: "HOD",
    position: "Professor and HOD",
    department: "Electrical and Electronics Engg.",
    institute: "Ph.D. (IIT-BHU)",
    domain: "Power Systems, Smart Grid Technologies",
    image: "/image/faculty/Dr. Lokesh Varshney.jpg",
  },
  {
    name: "Prof. V.K. Parashar",
    title: "Emirate Professor",
    position: "Professor",
    department: "Electrical & Electronics Engg.",
    institute: "B.Tech.(IIT), M.Tech.(IIT)",
    domain: "Electromagnetic Theory, Electrical Machines",
    image: "/image/faculty/Prof. V.K. Parashar.jpg",
  },
  {
    name: "Dr. Anil Kumar Rai",
    title: "Professor",
    position: "Professor",
    department: "Electrical and Electronics Engg.",
    institute: "Ph.D (IIT, Delhi), B.Sc. (Engg.)",
    domain: "Control Systems, Renewable Energy",
    image: "/image/faculty/Dr. Anil Kumar Rai.jpg",
  },
  {
    name: "Dr. J. G. Yadav",
    title: "Associate Professor",
    position: "Associate Professor",
    department: "Electrical & Electronics Engineering",
    institute: "M.Tech (MMMEC), Ph.D (UTU)",
    domain: "Power Electronics, Microgrids",
    image: "/image/faculty/Dr. J. G. Yadav.jpg",
  },
  {
    name: "Dr. Sarika Kalra",
    title: "Associate Professor",
    position: "Associate Professor",
    department: "Electrical and Electronics Engg.",
    institute: "Ph.D (MNNIT, Allahabad)",
    domain: "Signal Processing, Machine Learning",
    image: "/image/faculty/Dr. Sarika Kalra.jpg",
  },
  {
    name: "Dr. Vani Bhargava",
    title: "Associate Professor",
    position: "Assistant Professor",
    department: "EN",
    institute: "M.Tech (SATI), Ph.D(Amity)",
    domain: "Embedded Systems, Digital Electronics",
    image: "/image/faculty/Dr. Vani Bhargava.jpg",
  },
  {
    name: "Mr. Ritesh Sharma",
    title: "Assistant Professor",
    position: "Assistant Prof.",
    department: "EN",
    institute: "B.Tech, M.Tech (R.T.U, Kota)",
    domain: "High Voltage Engineering",
    image: "/image/faculty/Mr. Ritesh Sharma.jpg",
  },
  {
    name: "Ms. Navjyoti Sharma",
    title: "Assistant Professor",
    position: "Assistant Professor",
    department: "Electrical and Electronics",
    institute: "M.Tech (MANIT, Bhopal)",
    domain: "Electrical Drives, Power Systems",
    image: "/image/faculty/Ms. Navjyoti Sharma.jpg",
  },
  {
    name: "Mr. Ravinder Kumar",
    title: "Assistant Professor",
    position: "Assistant Professor",
    department: "Electrical & Electronics Engineering",
    institute: "B.Tech, M.Tech (R.T.U, Kota)",
    domain: "Power Transmission, Smart Grids",
    image: "/image/faculty/Mr. Ravinder Kumar.jpg",
  },
  {
    name: "Mr. Dinanath Prasad",
    title: "Assistant Professor",
    position: "Assistant Professor",
    department: "Electrical and Electronics",
    institute: "M.Tech (NIT, Hamirpur), Ph.D*",
    domain: "Renewable Energy, Control Systems",
    image: "/image/faculty/Mr. Dinanath Prasad.jpg",
  },
  {
    name: "Mr. Parveen Kumar",
    title: "Assistant Professor",
    position: "Assistant Professor",
    department: "Electrical & Electronics Engineering",
    institute: "B.Tech, M.Tech (DCRUST)",
    domain: "Digital Control Systems",
    image: "/image/faculty/Mr. Parveen Kumar.jpg",
  },
  {
    name: "Ms. Nupur Mittal",
    title: "Assistant Professor",
    position: "Assistant Professor",
    department: "EN",
    institute: "M.Tech (K.N.I.T), Ph.D*(DTU)",
    domain: "VLSI Design, Signal Processing",
    image: "/image/faculty/Ms. Nupur Mittal.jpeg",
  },
  {
    name: "Ms. Nidhi Singh",
    title: "Assistant Professor",
    position: "Assistant Professor",
    department: "Electrical & Electronics",
    institute: "M.Tech (SLIET, Punjab), Ph.D*",
    domain: "Control Systems, Renewable Energy",
    image: "/image/faculty/Ms. Nidhi Singh.jpg",
  },
  {
    name: "Mr. Gaurav Srivastava",
    title: "Assistant Professor",
    position: "Assistant Professor",
    department: "Electrical & Electronics Engineering",
    institute: "M.Tech (NIT, Hamirpur), Ph.D*(DTU)",
    domain: "Electrical Machines, Power Systems",
    image: "/image/faculty/Mr. Gaurav Srivastava.jpg",
  },
  {
    name: "Mr. Mahendra Dutt Diwivedi",
    title: "Assistant Professor",
    position: "Assistant Professor",
    department: "Electrical & Electronics Engg",
    institute: "M.Tech (IIT, Roorkee)",
    domain: "Electromagnetic Compatibility",
    image: "/image/faculty/Mr. Mahendra Dutt Diwivedi.jpg",
  },
  {
    name: "Mr. Neeraj Gupta",
    title: "Assistant Professor",
    position: "Assistant Professor",
    department: "EN",
    institute: "M.Tech (MNIT, Allahabad)",
    domain: "Microelectronics, Power Systems",
    image: "/image/faculty/Mr. Neeraj Gupta.jpg",
  },
  {
    name: "Mr. Mahesh Sharma",
    title: "Assistant Professor",
    position: "Assistant Professor",
    department: "Electrical & Electronics Engg",
    institute: "M.Tech (AKGU, Gzb)",
    domain: "Embedded Systems, Smart Grid Technologies",
    image: "/image/faculty/Mr. Mahesh Sharma.jpg",
  },
  {
    name: "Dr. Nitisha Shrivastava",
    title: "Assistant Professor",
    position: "Assistant Professor / Scientific Officer",
    department: "",
    institute: "M.Tech, Ph.D",
    domain: "Nanotechnology, Smart Materials",
    image: "/image/faculty/Dr. Nitisha Shrivastava.jpg",
  },
  {
    name: "Mr. Arun Kumar Maurya",
    title: "Assistant Professor",
    position: "Assistant Professor",
    department: "Electrical & Electronics Engg",
    institute: "M.Tech",
    domain: "Power Electronics, Electrical Drives",
    image: "/image/faculty/Mr. Arun Kumar Maurya.jpg",
  },
];
