export const coursesData = [
   {
    id: 1,
    courseName: "B.Tech in Computer Science Engineering",
    head: "4 Years",
    description: "Rs. 1,75,000 - Tuition Fee",
  },
   {
    id: 2,
    courseName: "B.Tech in Data Science",
    head: "4 Years",
    description: "Rs. 1,75,000 - Tuition Fee",
  },
   {
    id: 3,
    courseName: "B.Tech in Artificial Intelligence & Machine Learning",
    head: "4 Years",
    description: "Rs. 1,75,000 - Tuition Fee",
  },
   {
    id: 4,
    courseName: "B.Tech in Information Technology ",
    head: "4 Years",
    description: "Rs. 1,75,000 - Tuition Fee",
  },
   {
    id: 5,
    courseName: "B.Tech in Electronics & Communication",
    head: "4 Years",
    description: "Rs. 1,75,000 - Tuition Fee",
  },
   {
    id: 6,
    courseName: "B.Tech in Mechanical Engineering ",
    head: "4 Years",
    description: "Rs. 1,75,000 - Tuition Fee",
  },
   {
    id: 7,
    courseName: "B.Tech in Civil Engineering",
    head: "4 Years",
    description: "Rs. 1,75,000 - Tuition Fee",
  },
  {
    id: 8,
    courseName: "BBA – Bachelor of Business Administration",
    head: "3 Years",
    description: "Rs. 99,000 - Tuition Fee",
  },
  {
    id: 9,
    courseName: "BCA – Bachelor of Computer Applications",
    head: "3 Years",
    description: "Rs. 90,000 - Tuition Fee",
  },
  {
    id: 10,
    courseName: "M.Tech in Computer Science Engineering",
    head: "2 Years",
    description: "Rs. 1,30,000 - Tuition Fee",
  },
  {
    id: 11,
    courseName: "M.Tech in Electronics & Communication Engineering",
    head: "2 Years",
    description: "Rs. 1,30,000 - Tuition Fee",
  },
  {
    id: 12,
    courseName: "M.Tech in Electrical & Electronics Engineering",
    head: "2 Years",
    description: "Rs. 1,30,000 - Tuition Fee",
  },
  {
    id: 13,
    courseName: "M.Tech in Mechanical Engineering",
    head: "2 Years",
    description: "Rs. 1,30,000 - Tuition Fee",
  },
  {
    id: 14,
    courseName: "MCA – Master of Computer Applications",
    head: "2 Years",
    description: "Rs. 1,30,000 - Tuition Fee",
  },
  {
    id: 15,
    courseName: "MBA – Master of Business Administration (focus on modern management and leadership skills)",
    head: "2 Years",
    description: "Rs. 1,70,000 - Tuition Fee",
  },
  {
    id: 16,
    courseName: "Ph.D. programs",
    head: "Duration varies",
    description: "Rs. 75,000 - Tuition Fee",
  },
];